events { worker_connections 1024; }

http {
    server {
        listen 8080;

        # /api/products ile başlayanlar Product Service'e
        location /api/products {
            proxy_pass http://product-service:8081;
        }

        # /api/basket ile başlayanlar Basket Service'e
        location /api/basket {
            proxy_pass http://basket-service:8083;
        }
    }
}
