server.port=8090

eureka.client.service-url.defaultZone=http://discovery-service:9090/eureka/

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

management.endpoints.web.exposure.include=*
