server.port=8088
eureka.client.service-url.defaultZone=http://localhost:9090/eureka/

spring.cloud.gateway.server.webmvc.routes[0].id=product-service
# spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/products/**

spring.cloud.gateway.server.webmvc.routes[1].id=basket-service
# spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://BASKET-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/basket/**

spring.cloud.gateway.server.webmvc.routes[2].id=user-service
# spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/users/**

# jwt.secret=MyVerySecretKeyForQuantumShopJwtAuthentication123456
jwt.secret=QuantumShopSecretKeyQuantumShopSecretKeyQuantumShop