# spring.application.name=user-service
server.port=8085
spring.datasource.url=jdbc:postgresql://product-db:5432/product_db
spring.datasource.username=cengiz
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.threads.virtual.enabled=true
