
# spring.application.name=discovery-service

server.port=9090
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false
management.endpoints.web.exposure.include=*
eureka.instance.prefer-ip-address=true
spring.threads.virtual.enabled=true



