

spring.application.name=order-service
# server.port=8084
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=cengiz
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.threads.virtual.enabled=true     

