spring.application.name=product-service
spring.profiles.active=local
#  server.port=9081
# PostgreSQL Baglantisi:
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=cengiz
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Java 21 Sanal Thread'lerini aktif eder (Yüksek trafik yönetimi için)
spring.threads.virtual.enabled=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest





