server.port=8081
# spring.datasource.url=jdbc:postgresql://store-postgres:5432/product_db
spring.datasource.url=jdbc:postgresql://product-db:5432/product_db
spring.datasource.username=cengiz
spring.datasource.password=password123

spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=store-redis
spring.data.redis.port=6379

spring.rabbitmq.host=store-rabbitmq
spring.rabbitmq.port=5672


