# spring.application.name=basket-service
# server.port=8083
# Redis Bağlantısı (Docker içindeki servis adı)
# spring.data.redis.host=basket-cache
# spring.data.redis.port=6379
# spring.threads.virtual.enabled=true

# spring.application.name=basket-service
# server.port=8082  #adminer 8082 de calisiyor
# server.port=8085
# Redis
# spring.data.redis.host=localhost
# spring.data.redis.port=6379

# Container icinde artik localhost kullanmiyoruz: hostname = container adi oldu
# spring.application.name=basket-service
# spring.profiles.active=local
# server.port=8083
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

# RabbitMQ
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
#spring.threads.virtual.enabled=true

spring.profiles.active=local
# baska hicbir sey koyma (temiz config)

