
server.port=9083
spring.application.name=basket-service
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

eureka.client.service-url.defaultZone=http://localhost:9090/eureka
eureka.instance.prefer-ip-address=true

spring.threads.virtual.enabled=true